name: Hexo Auto Deploy
on:
  push:
    branches: [main] # 你的仓库主分支（如果是 master 就改成 master）
    paths:
      - 'source/_posts/**' # 只有修改文章才触发部署
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # 和你电脑上的 Node 版本一致（一般 16/18 都可以）
      - name: Install dependencies
        run: npm install hexo-cli -g && npm install
      - name: Deploy
        run: hexo clean && hexo g && hexo d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自动生成，不用改
